#ifndef PathData_H
#define PathData_H

#define ShaderPathPre "shaders/"
#define VertShaderPath ShaderPathPre "commonTexLight.vert"
#define FragShaderPath  ShaderPathPre "commonTexLight.frag"
#define VertShaderPath2 ShaderPathPre "dashboard2D.vert"
#define FragShaderPath2  ShaderPathPre "dashboard2D.frag"

#define _texturePre "assets/textures/"
#define back_texture _texturePre "back.dds"
#define dianjistart_texture _texturePre "dianjistart.dds"
#define resume_texture _texturePre "resume.dds"
#define guanyu_texture _texturePre "guanyu.dds"
#define about_texture _texturePre "about.dds"
#define steps_texture _texturePre "steps.dds"
#define exitbtn_texture _texturePre "exitbtn.dds"
#define grass_texture _texturePre "grass.dds"
#define cft_texture _texturePre "cft.dds"
#define floor_texture _texturePre "floor.dds"
#define zft_texture _texturePre "zft.dds"
#define box_texture _texturePre "box.dds"
#define dici_texture _texturePre "dici.dds"
#define jiazi_texture _texturePre "jiazi.dds"
#define cftshadow_texture _texturePre "cftshadow.dds"
#define qizi_texture _texturePre "qizi.dds"
#define qizigun_texture _texturePre "qizigun.dds"
#define tanshe_texture _texturePre "tanshe.dds"
#define musicbtn_texture _texturePre "musicbtn.dds"
#define musicclosebtn_texture _texturePre "musicclosebtn.dds"

#define ModelPathPre "assets/models/"
#define attach_obj ModelPathPre "attach.obj"
#define box_obj ModelPathPre "box.obj"
#define cft_obj ModelPathPre "cft.obj"
#define floor_obj ModelPathPre "floor.obj"
#define diaoluo_obj ModelPathPre "diaoluo.obj"
#define dici_obj ModelPathPre "dici.obj"
#define jiazijia_obj ModelPathPre "jiazijia.obj"
#define jiazike_obj ModelPathPre "jiazike.obj"
#define plane_obj ModelPathPre "plane.obj"
#define qizi_obj ModelPathPre "qizi.obj"
#define qizigun_obj ModelPathPre "qizigun.obj"
#define tanshe_obj ModelPathPre "tanshe.obj"
#define zft_obj ModelPathPre "zft.obj"
#define SoundPathPre "assets/sounds/"
#define bgmPath SoundPathPre "bgm.wav"
#define pointPath SoundPathPre "dingdong.wav"

#endif
